openapi: 3.0.2
servers:
  - url: 'http://localhost:8080'
    description: localhost
info:
  description: xiv-craftsmanship-api
  version: 1.0.0
  title: xiv-craftsmanship-api
  termsOfService: 'https://github.com/hazuki3417/xiv-craftsmanship-api'
  contact:
    url: 'https://github.com/hazuki3417/xiv-craftsmanship-web'
    email: hazuki3417@gmail.com
    name: hazuki3417
  license:
    name: MIT
    url: 'https://github.com/hazuki3417/xiv-craftsmanship-db'
paths:
  /craft:
    get:
      summary: craft
      tags:
        - craft
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Craft'
        '400':
          description: Bad Request
      operationId: get-craft
      parameters:
        - schema:
            type: string
          in: query
          name: name
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      description: craft
    parameters: []
  /health:
    get:
      summary: health
      tags:
        - health
      responses:
        '200':
          description: OK
      operationId: get-health
      description: health
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
  '/recipe/{recipeId}':
    get:
      summary: recipe
      tags:
        - recipe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Material'
        '400':
          description: Bad Request
        '404':
          description: Not Found
      operationId: get-recipe
      description: recipe
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
    parameters:
      - schema:
          type: string
        name: recipeId
        in: path
        required: true
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    Craft:
      title: Craft
      x-stoplight:
        id: kv5zpkg88x0ax
      type: object
      additionalProperties: false
      properties:
        recipeId:
          $ref: '#/components/schemas/RecipeId'
        itemId:
          $ref: '#/components/schemas/ItemId'
        name:
          type: string
          x-stoplight:
            id: hsckae7mm9j1m
        pieces:
          type: integer
          x-stoplight:
            id: kuy3sy67nju5e
          minimum: 1
          maximum: 999
        job:
          type: string
          x-stoplight:
            id: j91gqw1bgusp6
        itemLevel:
          type: integer
          x-stoplight:
            id: cmtv40zaoqy3c
          minimum: 1
          maximum: 999
          readOnly: true
        craftLevel:
          type: integer
          x-stoplight:
            id: 7t9io51fndra8
          minimum: 1
          maximum: 999
          nullable: true
          readOnly: true
      required:
        - recipeId
        - itemId
        - name
        - pieces
        - job
        - itemLevel
        - craftLevel
    RecipeId:
      title: RecipeId
      x-stoplight:
        id: 5lxsqfx98357g
      type: string
      pattern: '^[0-9a-z]{11}'
    ItemId:
      title: ItemId
      x-stoplight:
        id: cv35svuwmrclk
      type: string
      pattern: '^[0-9a-z]{11}'
    Recipe:
      title: Recipe
      x-stoplight:
        id: cqocrs77ylh56
      type: object
      additionalProperties: false
      properties:
        recipeId:
          $ref: '#/components/schemas/RecipeId'
        itemId:
          $ref: '#/components/schemas/ItemId'
        materials:
          type: array
          x-stoplight:
            id: rvvoppqcifnuw
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Material'
      required:
        - recipeId
        - itemId
        - materials
    Material:
      title: Material
      x-stoplight:
        id: 8b9jqdh25vrsb
      type: object
      additionalProperties: false
      properties:
        itemId:
          $ref: '#/components/schemas/ItemId'
        quantity:
          type: integer
          x-stoplight:
            id: zl5r7dvsm0ip2
          default: 1
          minimum: 1
          maximum: 999
        type:
          $ref: '#/components/schemas/ItemType'
        recipes:
          x-stoplight:
            id: 4jvv6s358u30a
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Recipe'
      required:
        - itemId
        - quantity
        - type
        - recipes
    ItemType:
      title: ItemType
      x-stoplight:
        id: zn5crzyo5c0sf
      type: string
      enum:
        - material
        - crystal
      description: ''
  requestBodies: {}
  securitySchemes: {}
  parameters: {}
tags:
  - name: craft
  - name: health
  - name: recipe
