// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * xiv-craftsmanship-api
 *
 * xiv-craftsmanship-api
 *
 * API version: 1.0.0
 * Contact: hazuki3417@gmail.com
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/hazuki3417/xiv-craftsmanship-api/go"
)

func main() {
	log.Printf("Server started")

	CraftAPIService := openapi.NewCraftAPIService()
	CraftAPIController := openapi.NewCraftAPIController(CraftAPIService)

	router := openapi.NewRouter(CraftAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
