// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Craft struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Depth struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Edge struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

type Node struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Unit     int    `json:"unit"`
	Total    int    `json:"total"`
	Depth    *Depth `json:"depth"`
	NodeType string `json:"node_type"`
}

type Query struct {
}

type RecipeTree struct {
	Nodes []*Node `json:"nodes"`
	Edges []*Edge `json:"edges"`
}
