// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Craft struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Material struct {
	ParentID   string `json:"parentId"`
	ChildID    string `json:"childId"`
	ParentName string `json:"parentName"`
	ChildName  string `json:"childName"`
	Unit       int    `json:"unit"`
	Total      int    `json:"total"`
}

type Query struct {
}
