// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * xiv-craftsmanship-api
 *
 * xiv-craftsmanship-api
 *
 * API version: 1.0.0
 * Contact: hazuki3417@gmail.com
 */

package openapi

import (
	"context"
	"net/http"
)



// CraftAPIRouter defines the required methods for binding the api requests to a responses for the CraftAPI
// The CraftAPIRouter implementation should parse necessary information from the http request,
// pass the data to a CraftAPIServicer to perform the required actions, then write the service results to the http response.
type CraftAPIRouter interface { 
	GetCraft(http.ResponseWriter, *http.Request)
}
// RecipeAPIRouter defines the required methods for binding the api requests to a responses for the RecipeAPI
// The RecipeAPIRouter implementation should parse necessary information from the http request,
// pass the data to a RecipeAPIServicer to perform the required actions, then write the service results to the http response.
type RecipeAPIRouter interface { 
	GetRecipe(http.ResponseWriter, *http.Request)
}


// CraftAPIServicer defines the api actions for the CraftAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CraftAPIServicer interface { 
	GetCraft(context.Context, string) (ImplResponse, error)
}


// RecipeAPIServicer defines the api actions for the RecipeAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type RecipeAPIServicer interface { 
	GetRecipe(context.Context, string) (ImplResponse, error)
}
