// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * xiv-craftsmanship-api
 *
 * xiv-craftsmanship-api
 *
 * API version: 1.0.0
 * Contact: hazuki3417@gmail.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// CraftAPIService is a service that implements the logic for the CraftAPIServicer
// This service should implement the business logic for every endpoint for the CraftAPI API.
// Include any external packages or services that will be required by this service.
type CraftAPIService struct {
}

// NewCraftAPIService creates a default api service
func NewCraftAPIService() *CraftAPIService {
	return &CraftAPIService{}
}

// GetCraft - craft
func (s *CraftAPIService) GetCraft(ctx context.Context, name string, body map[string]interface{}) (ImplResponse, error) {
	// TODO - update GetCraft with the required logic for this service method.
	// Add api_craft_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Craft{}) or use other options such as http.Ok ...
	// return Response(200, []Craft{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCraft method not implemented")
}
