// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * xiv-craftsmanship-api
 *
 * xiv-craftsmanship-api
 *
 * API version: 1.0.0
 * Contact: hazuki3417@gmail.com
 */

package openapi




type Recipe struct {

	RecipeId string `json:"recipeId" validate:"regexp=^[0-9a-z]{11}"`

	ItemId string `json:"itemId" validate:"regexp=^[0-9a-z]{11}"`

	Materials []Material `json:"materials"`
}

// AssertRecipeRequired checks if the required fields are not zero-ed
func AssertRecipeRequired(obj Recipe) error {
	elements := map[string]interface{}{
		"recipeId": obj.RecipeId,
		"itemId": obj.ItemId,
		"materials": obj.Materials,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Materials {
		if err := AssertMaterialRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecipeConstraints checks if the values respects the defined constraints
func AssertRecipeConstraints(obj Recipe) error {
	for _, el := range obj.Materials {
		if err := AssertMaterialConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
